#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Decode xlog fixtures and compare decoded payloads with expected fixture lines.

Usage:
  scripts/xlog/decode_compare.sh <fixture-root> [--decoder auto|official|py3]

Decoder modes:
  auto      Prefer official Python2 decoder if available; fallback to py3 nocrypt decoder.
  official  Force official decoder scripts in third_party/mars/mars/xlog/crypt.
  py3       Force scripts/xlog/decode_mars_nocrypt_py3.py (supports nocrypt only).

Input:
  <fixture-root> must contain manifest.tsv generated by scripts/xlog/gen_fixtures.sh.
EOF
}

if (($# < 1)); then
  usage
  exit 2
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"

fixture_root="$(cd "$1" && pwd)"
shift

decoder_mode="auto"
while (($# > 0)); do
  case "$1" in
    --decoder)
      decoder_mode="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

case "$decoder_mode" in
  auto|official|py3) ;;
  *)
    echo "--decoder must be one of: auto / official / py3" >&2
    exit 2
    ;;
esac

manifest="${fixture_root}/manifest.tsv"
if [[ ! -f "$manifest" ]]; then
  echo "manifest not found: $manifest" >&2
  exit 2
fi

py2_bin=""
if command -v python2 >/dev/null 2>&1; then
  py2_bin="python2"
elif command -v python >/dev/null 2>&1; then
  py_major="$(python - <<'PY'
import sys
print(sys.version_info[0])
PY
)"
  if [[ "$py_major" == "2" ]]; then
    py2_bin="python"
  fi
fi

official_nocrypt="${repo_root}/third_party/mars/mars/xlog/crypt/decode_mars_nocrypt_log_file.py"
official_crypt="${repo_root}/third_party/mars/mars/xlog/crypt/decode_mars_crypt_log_file.py"
py3_nocrypt="${repo_root}/scripts/xlog/decode_mars_nocrypt_py3.py"

decode_file() {
  local xlog_file="$1"
  local output_file="$2"
  local crypt="$3"

  if [[ "$decoder_mode" == "official" || ("$decoder_mode" == "auto" && -n "$py2_bin") ]]; then
    if [[ -z "$py2_bin" ]]; then
      echo "official decoder requested but python2 is unavailable" >&2
      return 2
    fi
    if [[ "$crypt" == "crypt" ]]; then
      "$py2_bin" "$official_crypt" "$xlog_file" "$output_file"
    else
      "$py2_bin" "$official_nocrypt" "$xlog_file" "$output_file"
    fi
    return 0
  fi

  if [[ "$crypt" == "crypt" ]]; then
    echo "py3 decoder mode does not support crypt fixtures: $xlog_file" >&2
    return 2
  fi
  python3 "$py3_nocrypt" "$xlog_file" "$output_file"
}

failures=0
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

echo "[decode] fixture root: $fixture_root"
echo "[decode] decoder mode: $decoder_mode"
if [[ "$decoder_mode" == "auto" ]]; then
  if [[ -n "$py2_bin" ]]; then
    echo "[decode] auto selected official decoder via $py2_bin"
  else
    echo "[decode] auto selected py3 nocrypt decoder"
  fi
fi

while IFS=$'\t' read -r backend compress mode crypt prefix count case_dir; do
  if [[ "$backend" == "backend" ]]; then
    continue
  fi

  if [[ ! -d "$case_dir" ]]; then
    echo "[fail] missing case dir: $case_dir"
    failures=$((failures + 1))
    continue
  fi

  xlogs=()
  while IFS= read -r xlog_file; do
    xlogs+=("$xlog_file")
  done < <(find "$case_dir" -maxdepth 1 -type f -name "*.xlog" | sort)
  if [[ "${#xlogs[@]}" -eq 0 ]]; then
    echo "[fail] no .xlog file in $case_dir"
    failures=$((failures + 1))
    continue
  fi

  decoded_dir="${case_dir}/decoded"
  rm -rf "$decoded_dir"
  mkdir -p "$decoded_dir"

  decode_ok=1
  for xlog_file in "${xlogs[@]}"; do
    decoded_file="${decoded_dir}/$(basename "$xlog_file").log"
    if ! decode_file "$xlog_file" "$decoded_file" "$crypt"; then
      echo "[fail] decode failed: $xlog_file"
      decode_ok=0
      break
    fi
  done
  if [[ "$decode_ok" != "1" ]]; then
    failures=$((failures + 1))
    continue
  fi

  if ! [[ "$count" =~ ^[0-9]+$ ]]; then
    echo "[fail] invalid count in manifest for $prefix: $count"
    failures=$((failures + 1))
    continue
  fi

  actual_file="${tmpdir}/${prefix}.actual"
  cat "${decoded_dir}"/*.log 2>/dev/null | grep -o "FIXTURE|${prefix}|[0-9][0-9][0-9][0-9]" > "$actual_file" || true

  expected_file="${tmpdir}/${prefix}.expected"
  : > "$expected_file"
  for ((i=0; i<count; i++)); do
    printf "FIXTURE|%s|%04d\n" "$prefix" "$i" >> "$expected_file"
  done

  if ! diff -u "$expected_file" "$actual_file" >/dev/null; then
    echo "[fail] payload mismatch for $prefix"
    diff -u "$expected_file" "$actual_file" || true
    failures=$((failures + 1))
    continue
  fi

  key="${compress}_${mode}_${crypt}"
  suffix_file="${tmpdir}/${backend}_${key}.suffix"
  cut -d'|' -f3 "$actual_file" > "$suffix_file"
  echo "[ok] $prefix"
done < "$manifest"

while IFS=$'\t' read -r backend compress mode crypt prefix count case_dir; do
  if [[ "$backend" == "backend" ]]; then
    continue
  fi
  if [[ "$backend" != "rust" ]]; then
    continue
  fi
  key="${compress}_${mode}_${crypt}"
  rust_file="${tmpdir}/rust_${key}.suffix"
  ffi_file="${tmpdir}/ffi_${key}.suffix"
  if [[ -f "$rust_file" && -f "$ffi_file" ]]; then
    if ! diff -u "$ffi_file" "$rust_file" >/dev/null; then
      echo "[fail] rust/ffi parity mismatch for $key"
      diff -u "$ffi_file" "$rust_file" || true
      failures=$((failures + 1))
    else
      echo "[ok] rust/ffi parity $key"
    fi
  fi
done < "$manifest"

if [[ "$failures" -ne 0 ]]; then
  echo
  echo "decode comparison completed with $failures failure(s)"
  exit 1
fi

echo
echo "decode comparison completed successfully"
